=== ouaburst/CT_GUI_Docker/Documentation/metadata-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Sample metadata",
  "description": "Description of the source/detector geometry.",
  "type": "object",
  "properties": {
    "GEOMETRY_ENGINE":      { "type": "string", "description": "Must be \"ODL\"" },
    "GEOMETRY_NAME":        { "type": "string", "description": "Must be \"ConeBeamGeometry\"" },
    "DET_NPX_X":            { "type": "integer", "description": "The number of sensor pixels in the X-axis. For ConeBeamGeometry this is the curved dimension." },
    "DET_NPX_Z":            { "type": "integer", "description": "The number of sensor pixels in the Z-axis. For ConeBeamGeometry this is the height dimension." },
    "DET_PIX_SIZE":         { "type": "number", "description": "The size of a single sensor pixel. Only square pixels are allowed currently." },
    "DET_X_MIN":            { "type": "number", "description": "The minimum point of the angle partition of the sensor. Measured in radians." },
    "DET_X_MAX":            { "type": "number", "description": "The maximum point of the angle partition of the sensor. Measured in radians." },
    "DET_Z_MIN":            { "type": "number", "description": "The minimum point of the sensor in the z-axis." },
    "DET_Z_MAX":            { "type": "number", "description": "The maximum point of the sensor in the z-axis." },
    "SRC_RADIUS":           { "type": "number", "description": "The radius of the source point."},
    "DET_RADIUS":           { "type": "number", "description": "The radius of the sensor point."},
    "DET_CURVATURE_RADIUS": { "type": "number", "description": "The curvature of the sensor." },
    "ROTATION_AXIS":        { "type": "array", "items": { "type": "number" }, "minItems": 3, "maxItems": 3, "description": "The axis of rotation." },
    "REC_PIC_SIZE":         { "type": "number", "description": "The default size of reconstruction voxels. Used in the auto-resolution feature." },
    "REC_NPX_X":            { "type": "integer", "description": "The default number of voxels in the X-axis for reconstructions." },
    "REC_NPX_Y":            { "type": "integer", "description": "The default number of voxels in the Y-axis for reconstructions." },
    "REC_NPX_Z":            { "type": "integer", "description": "The default number of voxels in the Z-axis for reconstructions." },
    "REC_MIN_X":            { "type": "number", "description": "The minimum point in the X-axis of the default reconstuction space. This is used as the default size for new regions of interest." },
    "REC_MAX_X":            { "type": "number", "description": "The maximum point in the X-axis of the default reconstuction space. This is used as the default size for new regions of interest." },
    "REC_MIN_Y":            { "type": "number", "description": "The minimum point in the Y-axis of the default reconstuction space. This is used as the default size for new regions of interest." },
    "REC_MAX_Y":            { "type": "number", "description": "The maximum point in the Y-axis of the default reconstuction space. This is used as the default size for new regions of interest." },
    "REC_MIN_Z":            { "type": "number", "description": "The minimum point in the Z-axis of the default reconstuction space. This is used as the default size for new regions of interest." },
    "REC_MAX_Z":            { "type": "number", "description": "The maximum point in the Z-axis of the default reconstuction space. This is used as the default size for new regions of interest." },
    "SINOGRAM_MIN":         { "type": "number", "description": "The minimum value in the sample's sinogram.npy file. Used to speed up sample switching." },
    "SINOGRAM_MAX":         { "type": "number", "description": "The maximum value in the sample's sinogram.npy file. Used to speed up sample switching." }
  },
  "required": ["GEOMETRY_ENGINE", "GEOMETRY_NAME", "DET_NPX_X", "DET_NPX_Z", "DET_PIX_SIZE", "DET_X_MIN", "DET_X_MAX", "DET_Z_MIN", "DET_Z_MAX", "SRC_RADIUS", "DET_RADIUS", "DET_CURVATURE_RADIUS", "ROTATION_AXIS", "REC_PIC_SIZE", "REC_NPX_X", "REC_NPX_Y", "REC_NPX_Z", "REC_MIN_X", "REC_MAX_X", "REC_MIN_Y", "REC_MAX_Y", "REC_MIN_Z", "REC_MAX_Z"]
}

=== ouaburst/CT_GUI_Docker/Documentation/metadata.json
{
    "GEOMETRY_ENGINE": "ODL",
    "GEOMETRY_NAME": "ConeBeamGeometry",
    "DET_NPX_Z": 512,
    "DET_NPX_X": 512,
    "DET_PIX_SIZE": 0.078125,
    "DET_X_MIN": -0.098174770424681035,
    "DET_X_MAX": 0.098174770424681035,
    "DET_Z_MIN": -20.0,
    "DET_Z_MAX": 20.0,
    "SRC_RADIUS": 200.0,
    "DET_RADIUS": 200.0,
    "DET_CURVATURE_RADIUS": 400.0,
    "ROTATION_AXIS": [0.0, 0.0, 1.0],
    "REC_PIC_SIZE": 0.13333333333333333,
    "REC_NPX_X": 300,
    "REC_NPX_Y": 300,
    "REC_NPX_Z": 300,
    "REC_MIN_X": -20.0,
    "REC_MAX_X": 20.0,
    "REC_MIN_Y": -20.0,
    "REC_MAX_Y": 20.0,
    "REC_MIN_Z": -20.0,
    "REC_MAX_Z": 20.0
}
